# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: recursive
  displayName: 'Checkout (with submodules)'

- task: UseDotNet@2
  displayName: 'Use DotNet 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Restore'
  inputs:
    command: 'restore'
    projects: 'FASTER.sln'
    feedsToUse: 'select'

- task: SonarCloudPrepare@4
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'foxlicorp'
    scannerMode: 'dotnet'
    projectKey: 'FASTER_App'
    projectName: 'FASTER_App'
    projectVersion: '$(Build.BuildNumber)'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Dotnet Build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Test (with coverage)'
  inputs:
    command: 'test'
    projects: 'FASTERTests/FASTERTests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore --no-build --collect:"Code Coverage"'

- task: SonarCloudAnalyze@4

- task: SonarCloudPublish@4
  displayName: 'Publish SonarCloud Quality Gate result'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish $(buildConfiguration) x64'
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) -r win-x64 --self-contained true --output $(Build.ArtifactStagingDirectory)\Release_x64'
    zipAfterPublish: True

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'FASTER_master_build'
    publishLocation: 'pipeline'