name: Publish

on:
  release:
    types: [released]

jobs:

  winget:
    runs-on: windows-latest
    steps:
      # Requires forked winget-pkgs: https://github.com/microsoft/winget-pkgs to the same account as this project
      - name: Submit to WinGet
        uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e #v2
        with:
          identifier: Foxlider.FASTER
          installers-regex: 'Release_x64.zip'
          max-versions-to-keep: 5
          # Classic Personal Access Token with [public_repo, workflow] scopes
          token: ${{ secrets.WINGET_TOKEN }} 